version: '3'

services:
  mondo-db:
    image: mongo:6.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ./data:/data/db

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mondo-db
      - ME_CONFIG_MONGODB_URL=mongodb://admin:password@mondo-db:27017
    depends_on:
      - mondo-db

  server:
    build: server/
    restart: always
    command: npm run dev
    ports:
      - "5000:5000"
    depends_on:
      - mondo-db

  client:
    build: client/
    restart: always
    command: npm start
    ports:
      - "3000:3000"
    network_mode: "host"
    depends_on:
      - server